name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Grant gradlew execute permission
      run: chmod +x ./gradlew

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # =====新增：接受SDK许可，安装SDK组件=====
    - name: Accept Android SDK licenses
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
    # ======================================

    - name: Build with Gradle Release APK
      run: ./gradlew assembleRelease

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk-build
        path: yuehong/build/outputs/apk/release/*.apk
