name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Grant gradlew execute permission
      run: chmod +x ./gradlew

    # 关键：改成 JDK17，适配 AGP 8.x
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Build with Gradle Release APK
      run: ./gradlew assembleRelease

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk-build
        # 这个项目主模块不是app，看项目结构是yuehong
        path: yuehong/build/outputs/apk/release/*.apk
